_BASE_: "CenterNet2_DLA-BiFPN-P5_640_24x_ST.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 68
  CENTERNET:
    NUM_CLASSES: 68
DATASETS:
  TRAIN: ("st_train",)
  TEST: ("st_val",)
TEST:
  EVAL_PERIOD: 20000
SOLVER:
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  MAX_ITER: 980000
  CHECKPOINT_PERIOD: 20000
  BASE_LR: 0.0001
  IMS_PER_BATCH: 8